# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Set new prefix key to Ctrl+Space
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Mouse support
set -g mouse on

# Use 1-based indexing
set -g base-index 1
setw -g pane-base-index 1

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

# Load Rose Pine theme config
source-file ~/.config/tmux/rosepine.conf

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
